### ISSUE TITLE
Rest call to get patch from previous patch month

### ISSUE THREAD

**Issue by jmajeti** [tseward/SharePointUpdates#5]
rest call to get  latest patch minus 1. We usually are one patch behind and instead of updating the script monthly with KB's . .it would be nice to use rest call for getting one cycle back patch.

**Comment by tseward** [comment]
@jmajeti tell me if this will work. Because 2016/2019 have two patches, I need to do a version comparison. The call will be:

`/api/Articles/previous/SharePoint%20Server%202016/PU`

The patches are ordered by descending build number. Because _typically_ 2016/2019 have two patches for the same month, I can't simply take the previous patch (since it'll be from the same month), so instead we compare the build number in the first and second element in the `List` -- if they're the same, we return the third (previous month, hopefully) otherwise we return the second in the array.

**Comment by jmajeti** [comment]
@tseward It should work. Thanks for considering.

**Comment by tseward** [comment]
This has been pushed to prod. Less reliable with 2013 and below, but works fine with 2016+.
